services:
  ubuntu:
    container_name: ubuntu
    hostname: ubuntu.guest
    image: ubuntu:latest
    networks:
      default:
      dev_net:
        ipv4_address: "10.0.0.2"
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
    restart: unless-stopped
  fedora:
    container_name: fedora
    hostname: fedora.guest
    image: fedora:latest
    networks:
      dev_net:
        ipv4_address: "10.0.0.3"
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
    restart: unless-stopped
  debian:
    container_name: debian
    hostname: debian.guest
    image: debian:latest
    networks:
      dev_net:
        ipv4_address: "10.0.0.4"
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
    restart: unless-stopped
  alpine:
    container_name: alpine
    hostname: alpine.guest
    image: alpine:latest
    networks:
      dev_net:
        ipv4_address: "10.0.0.5"
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
    restart: unless-stopped
networks:
  dev_net:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
